### ISSUE TITLE
Add option to skip user verification

### ISSUE THREAD

**Issue by eduardolundgren** [wedeploy/wedeploy-middleware#10]
For every request it's [verifying the user against the auth API](https://github.com/wedeploy/wedeploy-middleware/blob/master/auth.js#L162), although in some cases the user can skip that if the user is already loaded in `req.session` for example. 

Adding an option that can allow the user define when to skip the user verification will help in this case.

**Comment by NolanChan** [comment]
Finished in https://github.com/wedeploy/wedeploy-middleware/pull/11, @eduardolundgren I can't close. Can you close?
